name: Terraform Testing
on:[push]
jobs:
  Terraform-Fmt-Validate:
      runs-on: ubuntu-latest 
      steps:
        - run: echo "Testing our first wokflow"

        - name: Checkout
          uses: actions/checkout@v3

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v1

        - name: Terraform Init
          env: 
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: "us-east-1"
          run: terraform init 

        - name: Terraform Format
          run: terraform fmt -check

        - name: Terraform Validate
          run: terraform validate



